name: "\U0001F680 Feature Request"
title: 'idea: '
description: "Suggest an idea for this project \U0001F63B!"
projects: ["menloresearch/30"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Problem Statement"
      description: "Describe the problem you're facing"
      placeholder: |
        I'm always frustrated when ...

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Feature Idea"
      description: "Describe what you want instead. Examples are welcome!"
