name: "\U0001F31F Epic"
description: "Major building block that advances Jan's goals"
title: 'epic: '
type: "Epic"
projects: ["menloresearch/30"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Goal"
      description: "Describe the epic's objective and expected impact"
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Tasklist"
      description: "List the key tasks required to complete this epic"
  - type: textarea
    attributes:
      label: "Out of scope"
      description: "List items that are explicitly excluded from this epic"
