name: "\U0001F3AF Goal"
description: "External communication of Jan's roadmap and objectives"
title: 'goal: '
type: "Goal"
projects: ["menloresearch/30"]
assignees: freelerobot
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Goal"
      description: "Describe the objective and desired outcome"
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Tasklist"
      description: "List the specific tasks needed to achieve this goal"
  - type: textarea
    attributes:
      label: "Out of scope"
      description: "List items that are explicitly excluded from this goal"
