blank_issues_enabled: false
contact_links:
  - name: Jan Discussions
    url: https://github.com/orgs/menloresearch/discussions/categories/q-a
    about: Get help, discuss features & roadmap, and share your projects
