name: "\U0001F31F Epic"
description: "Major building block that push us toward Jan Goal"
title: 'goal: '
type: "Epic"
projects: ["menloresearch/30"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Goal"
      description: "Describe the conten of the goal"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Tasklist"
      description: "List of task to complete to reach the goal"

  - type: textarea
    attributes:
      label: "Out of scope"
      description: "List of things that is out of scope for this goal"
