name: "Goal"
description: "Communicate externally the roadmap/goal that Jan is heading toward"
title: 'goal: '
type: "Goal"
assignees: freelerobot
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Goal"
      description: "Describe the conten of the goal"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Tasklist"
      description: "List of task to complete to reach the goal"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Out of scope"
      description: "List of things that is out of scope for this goal"
